name = "get-favicon"
compatibility_date = "2023-05-01"

[site]
bucket = "."

[build]
command = ""

[[routes]]
pattern = "/api/favicon"
function = "api/favicon"

[[routes]]
pattern = "/"
function = "index"
